<?php

namespace Proxies\__CG__\MINSAL\IndicadoresBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrigenDatos extends \MINSAL\IndicadoresBundle\Entity\OrigenDatos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'nombre', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'sentenciaSql', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'conexiones', 'archivoNombre', 'file', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esFusionado', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esPivote', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esCatalogo', 'nombreCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'camposFusionados', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fusiones', 'areaCosteo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'campos', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'variables');
        }

        return array('__isInitialized__', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'id', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'nombre', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'descripcion', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'sentenciaSql', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'conexiones', 'archivoNombre', 'file', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esFusionado', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esPivote', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'esCatalogo', 'nombreCatalogo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'camposFusionados', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'fusiones', 'areaCosteo', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'campos', '' . "\0" . 'MINSAL\\IndicadoresBundle\\Entity\\OrigenDatos' . "\0" . 'variables');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrigenDatos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function upload($basepath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array($basepath));

        return parent::upload($basepath);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchivoNombre($archivoNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchivoNombre', array($archivoNombre));

        return parent::setArchivoNombre($archivoNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivoNombre', array());

        return parent::getArchivoNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentenciaSql($sentenciaSql)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentenciaSql', array($sentenciaSql));

        return parent::setSentenciaSql($sentenciaSql);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentenciaSql()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentenciaSql', array());

        return parent::getSentenciaSql();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsFusionado($esFusionado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsFusionado', array($esFusionado));

        return parent::setEsFusionado($esFusionado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsFusionado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsFusionado', array());

        return parent::getEsFusionado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamposFusionados($camposFusionados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamposFusionados', array($camposFusionados));

        return parent::setCamposFusionados($camposFusionados);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamposFusionados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamposFusionados', array());

        return parent::getCamposFusionados();
    }

    /**
     * {@inheritDoc}
     */
    public function addFusione(\MINSAL\IndicadoresBundle\Entity\OrigenDatos $fusiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFusione', array($fusiones));

        return parent::addFusione($fusiones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFusione(\MINSAL\IndicadoresBundle\Entity\OrigenDatos $fusiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFusione', array($fusiones));

        return parent::removeFusione($fusiones);
    }

    /**
     * {@inheritDoc}
     */
    public function getFusiones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFusiones', array());

        return parent::getFusiones();
    }

    /**
     * {@inheritDoc}
     */
    public function addCampo(\MINSAL\IndicadoresBundle\Entity\Campo $campos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCampo', array($campos));

        return parent::addCampo($campos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCampo(\MINSAL\IndicadoresBundle\Entity\Campo $campos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCampo', array($campos));

        return parent::removeCampo($campos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampos', array());

        return parent::getCampos();
    }

    /**
     * {@inheritDoc}
     */
    public function getCamposCalculados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamposCalculados', array());

        return parent::getCamposCalculados();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllFields', array());

        return parent::getAllFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setEsCatalogo($esCatalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsCatalogo', array($esCatalogo));

        return parent::setEsCatalogo($esCatalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsCatalogo', array());

        return parent::getEsCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCatalogo($nombreCatalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCatalogo', array($nombreCatalogo));

        return parent::setNombreCatalogo($nombreCatalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCatalogo', array());

        return parent::getNombreCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addVariable(\MINSAL\IndicadoresBundle\Entity\VariableDato $variables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVariable', array($variables));

        return parent::addVariable($variables);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVariable(\MINSAL\IndicadoresBundle\Entity\VariableDato $variables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVariable', array($variables));

        return parent::removeVariable($variables);
    }

    /**
     * {@inheritDoc}
     */
    public function getVariables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariables', array());

        return parent::getVariables();
    }

    /**
     * {@inheritDoc}
     */
    public function addConexione(\MINSAL\IndicadoresBundle\Entity\Conexion $conexiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConexione', array($conexiones));

        return parent::addConexione($conexiones);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConexione(\MINSAL\IndicadoresBundle\Entity\Conexion $conexiones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConexione', array($conexiones));

        return parent::removeConexione($conexiones);
    }

    /**
     * {@inheritDoc}
     */
    public function getConexiones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConexiones', array());

        return parent::getConexiones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsPivote($esPivote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsPivote', array($esPivote));

        return parent::setEsPivote($esPivote);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsPivote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsPivote', array());

        return parent::getEsPivote();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaCosteo($areaCosteo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaCosteo', array($areaCosteo));

        return parent::setAreaCosteo($areaCosteo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaCosteo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaCosteo', array());

        return parent::getAreaCosteo();
    }

}
